services:
  db:
    container_name: postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: shreyas
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  shreyas-full-stack-api:
    container_name: shreyas-full-stack-professional-api-container
    image: shreyas957/shreyas-full-stack-professional-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart:  unless-stopped
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5432/customer
networks:
  db:
    driver: bridge

volumes:
  db: